// Generated by `supabase gen types typescript --project-id <id>`
// Run: pnpm supabase gen types typescript --project-id YOUR_PROJECT_ID > src/infrastructure/database/types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

// Permissive placeholder until real types are generated. Replace by running:
//   pnpm supabase gen types typescript --project-id YOUR_PROJECT_ID > src/infrastructure/database/types.ts
type GenericTable = {
  Row: Record<string, unknown>;
  Insert: Record<string, unknown>;
  Update: Record<string, unknown>;
  Relationships: [];
};

export interface Database {
  public: {
    Tables: { [name: string]: GenericTable };
    Views: { [name: string]: { Row: Record<string, unknown>; Relationships: [] } };
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
