// Generated by `supabase gen types typescript --project-id <id>`
// Run: pnpm supabase gen types typescript --project-id YOUR_PROJECT_ID > src/infrastructure/database/types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}
